name: Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:headless

    - name: Build
      run: npm run build:prod
      
    - name: check directory
      run: ls -l dist

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.2.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: dist/tailwindAngular # The folder the action should deploy.
